// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scene.proto

#ifndef PROTOBUF_scene_2eproto__INCLUDED
#define PROTOBUF_scene_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "color.pb.h"
#include "fog.pb.h"
#include "sky.pb.h"
#include "light.pb.h"
#include "joint.pb.h"
#include "model.pb.h"
#include <boost/shared_ptr.hpp>
#include "MsgFactory.h"
// @@protoc_insertion_point(includes)

namespace experimot {
namespace msgs {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_scene_2eproto();
void protobuf_AssignDesc_scene_2eproto();
void protobuf_ShutdownFile_scene_2eproto();

class Scene;

// ===================================================================

class Scene : public ::google::protobuf::Message {
 public:
  Scene();
  virtual ~Scene();

  Scene(const Scene& from);

  inline Scene& operator=(const Scene& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Scene& default_instance();

  void Swap(Scene* other);

  // implements Message ----------------------------------------------

  inline Scene* New() const { return New(NULL); }

  Scene* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Scene& from);
  void MergeFrom(const Scene& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Scene* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional .experimot.msgs.Color ambient = 2;
  bool has_ambient() const;
  void clear_ambient();
  static const int kAmbientFieldNumber = 2;
  const ::experimot::msgs::Color& ambient() const;
  ::experimot::msgs::Color* mutable_ambient();
  ::experimot::msgs::Color* release_ambient();
  void set_allocated_ambient(::experimot::msgs::Color* ambient);

  // optional .experimot.msgs.Color background = 3;
  bool has_background() const;
  void clear_background();
  static const int kBackgroundFieldNumber = 3;
  const ::experimot::msgs::Color& background() const;
  ::experimot::msgs::Color* mutable_background();
  ::experimot::msgs::Color* release_background();
  void set_allocated_background(::experimot::msgs::Color* background);

  // optional .experimot.msgs.Sky sky = 4;
  bool has_sky() const;
  void clear_sky();
  static const int kSkyFieldNumber = 4;
  const ::experimot::msgs::Sky& sky() const;
  ::experimot::msgs::Sky* mutable_sky();
  ::experimot::msgs::Sky* release_sky();
  void set_allocated_sky(::experimot::msgs::Sky* sky);

  // optional bool shadows = 5 [default = true];
  bool has_shadows() const;
  void clear_shadows();
  static const int kShadowsFieldNumber = 5;
  bool shadows() const;
  void set_shadows(bool value);

  // optional .experimot.msgs.Fog fog = 6;
  bool has_fog() const;
  void clear_fog();
  static const int kFogFieldNumber = 6;
  const ::experimot::msgs::Fog& fog() const;
  ::experimot::msgs::Fog* mutable_fog();
  ::experimot::msgs::Fog* release_fog();
  void set_allocated_fog(::experimot::msgs::Fog* fog);

  // optional bool grid = 7;
  bool has_grid() const;
  void clear_grid();
  static const int kGridFieldNumber = 7;
  bool grid() const;
  void set_grid(bool value);

  // repeated .experimot.msgs.Model model = 8;
  int model_size() const;
  void clear_model();
  static const int kModelFieldNumber = 8;
  const ::experimot::msgs::Model& model(int index) const;
  ::experimot::msgs::Model* mutable_model(int index);
  ::experimot::msgs::Model* add_model();
  const ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Model >&
      model() const;
  ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Model >*
      mutable_model();

  // repeated .experimot.msgs.Light light = 9;
  int light_size() const;
  void clear_light();
  static const int kLightFieldNumber = 9;
  const ::experimot::msgs::Light& light(int index) const;
  ::experimot::msgs::Light* mutable_light(int index);
  ::experimot::msgs::Light* add_light();
  const ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Light >&
      light() const;
  ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Light >*
      mutable_light();

  // repeated .experimot.msgs.Joint joint = 10;
  int joint_size() const;
  void clear_joint();
  static const int kJointFieldNumber = 10;
  const ::experimot::msgs::Joint& joint(int index) const;
  ::experimot::msgs::Joint* mutable_joint(int index);
  ::experimot::msgs::Joint* add_joint();
  const ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Joint >&
      joint() const;
  ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Joint >*
      mutable_joint();

  // @@protoc_insertion_point(class_scope:experimot.msgs.Scene)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_ambient();
  inline void clear_has_ambient();
  inline void set_has_background();
  inline void clear_has_background();
  inline void set_has_sky();
  inline void clear_has_sky();
  inline void set_has_shadows();
  inline void clear_has_shadows();
  inline void set_has_fog();
  inline void clear_has_fog();
  inline void set_has_grid();
  inline void clear_has_grid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::experimot::msgs::Color* ambient_;
  ::experimot::msgs::Color* background_;
  ::experimot::msgs::Sky* sky_;
  ::experimot::msgs::Fog* fog_;
  ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Model > model_;
  ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Light > light_;
  ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Joint > joint_;
  bool shadows_;
  bool grid_;
  friend void  protobuf_AddDesc_scene_2eproto();
  friend void protobuf_AssignDesc_scene_2eproto();
  friend void protobuf_ShutdownFile_scene_2eproto();

  void InitAsDefaultInstance();
  static Scene* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Scene

// required string name = 1;
inline bool Scene::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Scene::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Scene::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Scene::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Scene::name() const {
  // @@protoc_insertion_point(field_get:experimot.msgs.Scene.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Scene::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:experimot.msgs.Scene.name)
}
inline void Scene::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:experimot.msgs.Scene.name)
}
inline void Scene::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:experimot.msgs.Scene.name)
}
inline ::std::string* Scene::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:experimot.msgs.Scene.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Scene::release_name() {
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Scene::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:experimot.msgs.Scene.name)
}

// optional .experimot.msgs.Color ambient = 2;
inline bool Scene::has_ambient() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Scene::set_has_ambient() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Scene::clear_has_ambient() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Scene::clear_ambient() {
  if (ambient_ != NULL) ambient_->::experimot::msgs::Color::Clear();
  clear_has_ambient();
}
inline const ::experimot::msgs::Color& Scene::ambient() const {
  // @@protoc_insertion_point(field_get:experimot.msgs.Scene.ambient)
  return ambient_ != NULL ? *ambient_ : *default_instance_->ambient_;
}
inline ::experimot::msgs::Color* Scene::mutable_ambient() {
  set_has_ambient();
  if (ambient_ == NULL) {
    ambient_ = new ::experimot::msgs::Color;
  }
  // @@protoc_insertion_point(field_mutable:experimot.msgs.Scene.ambient)
  return ambient_;
}
inline ::experimot::msgs::Color* Scene::release_ambient() {
  clear_has_ambient();
  ::experimot::msgs::Color* temp = ambient_;
  ambient_ = NULL;
  return temp;
}
inline void Scene::set_allocated_ambient(::experimot::msgs::Color* ambient) {
  delete ambient_;
  ambient_ = ambient;
  if (ambient) {
    set_has_ambient();
  } else {
    clear_has_ambient();
  }
  // @@protoc_insertion_point(field_set_allocated:experimot.msgs.Scene.ambient)
}

// optional .experimot.msgs.Color background = 3;
inline bool Scene::has_background() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Scene::set_has_background() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Scene::clear_has_background() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Scene::clear_background() {
  if (background_ != NULL) background_->::experimot::msgs::Color::Clear();
  clear_has_background();
}
inline const ::experimot::msgs::Color& Scene::background() const {
  // @@protoc_insertion_point(field_get:experimot.msgs.Scene.background)
  return background_ != NULL ? *background_ : *default_instance_->background_;
}
inline ::experimot::msgs::Color* Scene::mutable_background() {
  set_has_background();
  if (background_ == NULL) {
    background_ = new ::experimot::msgs::Color;
  }
  // @@protoc_insertion_point(field_mutable:experimot.msgs.Scene.background)
  return background_;
}
inline ::experimot::msgs::Color* Scene::release_background() {
  clear_has_background();
  ::experimot::msgs::Color* temp = background_;
  background_ = NULL;
  return temp;
}
inline void Scene::set_allocated_background(::experimot::msgs::Color* background) {
  delete background_;
  background_ = background;
  if (background) {
    set_has_background();
  } else {
    clear_has_background();
  }
  // @@protoc_insertion_point(field_set_allocated:experimot.msgs.Scene.background)
}

// optional .experimot.msgs.Sky sky = 4;
inline bool Scene::has_sky() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Scene::set_has_sky() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Scene::clear_has_sky() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Scene::clear_sky() {
  if (sky_ != NULL) sky_->::experimot::msgs::Sky::Clear();
  clear_has_sky();
}
inline const ::experimot::msgs::Sky& Scene::sky() const {
  // @@protoc_insertion_point(field_get:experimot.msgs.Scene.sky)
  return sky_ != NULL ? *sky_ : *default_instance_->sky_;
}
inline ::experimot::msgs::Sky* Scene::mutable_sky() {
  set_has_sky();
  if (sky_ == NULL) {
    sky_ = new ::experimot::msgs::Sky;
  }
  // @@protoc_insertion_point(field_mutable:experimot.msgs.Scene.sky)
  return sky_;
}
inline ::experimot::msgs::Sky* Scene::release_sky() {
  clear_has_sky();
  ::experimot::msgs::Sky* temp = sky_;
  sky_ = NULL;
  return temp;
}
inline void Scene::set_allocated_sky(::experimot::msgs::Sky* sky) {
  delete sky_;
  sky_ = sky;
  if (sky) {
    set_has_sky();
  } else {
    clear_has_sky();
  }
  // @@protoc_insertion_point(field_set_allocated:experimot.msgs.Scene.sky)
}

// optional bool shadows = 5 [default = true];
inline bool Scene::has_shadows() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Scene::set_has_shadows() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Scene::clear_has_shadows() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Scene::clear_shadows() {
  shadows_ = true;
  clear_has_shadows();
}
inline bool Scene::shadows() const {
  // @@protoc_insertion_point(field_get:experimot.msgs.Scene.shadows)
  return shadows_;
}
inline void Scene::set_shadows(bool value) {
  set_has_shadows();
  shadows_ = value;
  // @@protoc_insertion_point(field_set:experimot.msgs.Scene.shadows)
}

// optional .experimot.msgs.Fog fog = 6;
inline bool Scene::has_fog() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Scene::set_has_fog() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Scene::clear_has_fog() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Scene::clear_fog() {
  if (fog_ != NULL) fog_->::experimot::msgs::Fog::Clear();
  clear_has_fog();
}
inline const ::experimot::msgs::Fog& Scene::fog() const {
  // @@protoc_insertion_point(field_get:experimot.msgs.Scene.fog)
  return fog_ != NULL ? *fog_ : *default_instance_->fog_;
}
inline ::experimot::msgs::Fog* Scene::mutable_fog() {
  set_has_fog();
  if (fog_ == NULL) {
    fog_ = new ::experimot::msgs::Fog;
  }
  // @@protoc_insertion_point(field_mutable:experimot.msgs.Scene.fog)
  return fog_;
}
inline ::experimot::msgs::Fog* Scene::release_fog() {
  clear_has_fog();
  ::experimot::msgs::Fog* temp = fog_;
  fog_ = NULL;
  return temp;
}
inline void Scene::set_allocated_fog(::experimot::msgs::Fog* fog) {
  delete fog_;
  fog_ = fog;
  if (fog) {
    set_has_fog();
  } else {
    clear_has_fog();
  }
  // @@protoc_insertion_point(field_set_allocated:experimot.msgs.Scene.fog)
}

// optional bool grid = 7;
inline bool Scene::has_grid() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Scene::set_has_grid() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Scene::clear_has_grid() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Scene::clear_grid() {
  grid_ = false;
  clear_has_grid();
}
inline bool Scene::grid() const {
  // @@protoc_insertion_point(field_get:experimot.msgs.Scene.grid)
  return grid_;
}
inline void Scene::set_grid(bool value) {
  set_has_grid();
  grid_ = value;
  // @@protoc_insertion_point(field_set:experimot.msgs.Scene.grid)
}

// repeated .experimot.msgs.Model model = 8;
inline int Scene::model_size() const {
  return model_.size();
}
inline void Scene::clear_model() {
  model_.Clear();
}
inline const ::experimot::msgs::Model& Scene::model(int index) const {
  // @@protoc_insertion_point(field_get:experimot.msgs.Scene.model)
  return model_.Get(index);
}
inline ::experimot::msgs::Model* Scene::mutable_model(int index) {
  // @@protoc_insertion_point(field_mutable:experimot.msgs.Scene.model)
  return model_.Mutable(index);
}
inline ::experimot::msgs::Model* Scene::add_model() {
  // @@protoc_insertion_point(field_add:experimot.msgs.Scene.model)
  return model_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Model >&
Scene::model() const {
  // @@protoc_insertion_point(field_list:experimot.msgs.Scene.model)
  return model_;
}
inline ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Model >*
Scene::mutable_model() {
  // @@protoc_insertion_point(field_mutable_list:experimot.msgs.Scene.model)
  return &model_;
}

// repeated .experimot.msgs.Light light = 9;
inline int Scene::light_size() const {
  return light_.size();
}
inline void Scene::clear_light() {
  light_.Clear();
}
inline const ::experimot::msgs::Light& Scene::light(int index) const {
  // @@protoc_insertion_point(field_get:experimot.msgs.Scene.light)
  return light_.Get(index);
}
inline ::experimot::msgs::Light* Scene::mutable_light(int index) {
  // @@protoc_insertion_point(field_mutable:experimot.msgs.Scene.light)
  return light_.Mutable(index);
}
inline ::experimot::msgs::Light* Scene::add_light() {
  // @@protoc_insertion_point(field_add:experimot.msgs.Scene.light)
  return light_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Light >&
Scene::light() const {
  // @@protoc_insertion_point(field_list:experimot.msgs.Scene.light)
  return light_;
}
inline ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Light >*
Scene::mutable_light() {
  // @@protoc_insertion_point(field_mutable_list:experimot.msgs.Scene.light)
  return &light_;
}

// repeated .experimot.msgs.Joint joint = 10;
inline int Scene::joint_size() const {
  return joint_.size();
}
inline void Scene::clear_joint() {
  joint_.Clear();
}
inline const ::experimot::msgs::Joint& Scene::joint(int index) const {
  // @@protoc_insertion_point(field_get:experimot.msgs.Scene.joint)
  return joint_.Get(index);
}
inline ::experimot::msgs::Joint* Scene::mutable_joint(int index) {
  // @@protoc_insertion_point(field_mutable:experimot.msgs.Scene.joint)
  return joint_.Mutable(index);
}
inline ::experimot::msgs::Joint* Scene::add_joint() {
  // @@protoc_insertion_point(field_add:experimot.msgs.Scene.joint)
  return joint_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Joint >&
Scene::joint() const {
  // @@protoc_insertion_point(field_list:experimot.msgs.Scene.joint)
  return joint_;
}
inline ::google::protobuf::RepeatedPtrField< ::experimot::msgs::Joint >*
Scene::mutable_joint() {
  // @@protoc_insertion_point(field_mutable_list:experimot.msgs.Scene.joint)
  return &joint_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef boost::shared_ptr<experimot::msgs::Scene> ScenePtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace experimot

typedef const boost::shared_ptr<experimot::msgs::Scene const> ConstScenePtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_scene_2eproto__INCLUDED
