// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model_v.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "model_v.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Indriya {
namespace Core {
namespace Msgs {

namespace {

const ::google::protobuf::Descriptor* Model_V_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Model_V_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_model_5fv_2eproto() {
  protobuf_AddDesc_model_5fv_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "model_v.proto");
  GOOGLE_CHECK(file != NULL);
  Model_V_descriptor_ = file->message_type(0);
  static const int Model_V_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Model_V, models_),
  };
  Model_V_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Model_V_descriptor_,
      Model_V::default_instance_,
      Model_V_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Model_V, _has_bits_[0]),
      -1,
      -1,
      sizeof(Model_V),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Model_V, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_model_5fv_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Model_V_descriptor_, &Model_V::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_model_5fv_2eproto() {
  delete Model_V::default_instance_;
  delete Model_V_reflection_;
}

void protobuf_AddDesc_model_5fv_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Indriya::Core::Msgs::protobuf_AddDesc_model_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rmodel_v.proto\022\021Indriya.Core.Msgs\032\013mode"
    "l.proto\"3\n\007Model_V\022(\n\006models\030\002 \003(\0132\030.Ind"
    "riya.Core.Msgs.Model", 100);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "model_v.proto", &protobuf_RegisterTypes);
  Model_V::default_instance_ = new Model_V();
  Model_V::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_model_5fv_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_model_5fv_2eproto {
  StaticDescriptorInitializer_model_5fv_2eproto() {
    protobuf_AddDesc_model_5fv_2eproto();
  }
} static_descriptor_initializer_model_5fv_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int Model_V::kModelsFieldNumber;
#endif  // !_MSC_VER

Model_V::Model_V()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Indriya.Core.Msgs.Model_V)
}

void Model_V::InitAsDefaultInstance() {
}

Model_V::Model_V(const Model_V& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Indriya.Core.Msgs.Model_V)
}

void Model_V::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Model_V::~Model_V() {
  // @@protoc_insertion_point(destructor:Indriya.Core.Msgs.Model_V)
  SharedDtor();
}

void Model_V::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Model_V::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Model_V::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Model_V_descriptor_;
}

const Model_V& Model_V::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_model_5fv_2eproto();
  return *default_instance_;
}

Model_V* Model_V::default_instance_ = NULL;

Model_V* Model_V::New(::google::protobuf::Arena* arena) const {
  Model_V* n = new Model_V;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Model_V::Clear() {
  models_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Model_V::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Indriya.Core.Msgs.Model_V)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Indriya.Core.Msgs.Model models = 2;
      case 2: {
        if (tag == 18) {
         parse_models:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_models()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_models;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Indriya.Core.Msgs.Model_V)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Indriya.Core.Msgs.Model_V)
  return false;
#undef DO_
}

void Model_V::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Indriya.Core.Msgs.Model_V)
  // repeated .Indriya.Core.Msgs.Model models = 2;
  for (unsigned int i = 0, n = this->models_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->models(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Indriya.Core.Msgs.Model_V)
}

::google::protobuf::uint8* Model_V::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Indriya.Core.Msgs.Model_V)
  // repeated .Indriya.Core.Msgs.Model models = 2;
  for (unsigned int i = 0, n = this->models_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->models(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Indriya.Core.Msgs.Model_V)
  return target;
}

int Model_V::ByteSize() const {
  int total_size = 0;

  // repeated .Indriya.Core.Msgs.Model models = 2;
  total_size += 1 * this->models_size();
  for (int i = 0; i < this->models_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->models(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Model_V::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Model_V* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Model_V*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Model_V::MergeFrom(const Model_V& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  models_.MergeFrom(from.models_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Model_V::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Model_V::CopyFrom(const Model_V& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Model_V::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->models())) return false;
  return true;
}

void Model_V::Swap(Model_V* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Model_V::InternalSwap(Model_V* other) {
  models_.UnsafeArenaSwap(&other->models_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Model_V::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Model_V_descriptor_;
  metadata.reflection = Model_V_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Model_V

// repeated .Indriya.Core.Msgs.Model models = 2;
 int Model_V::models_size() const {
  return models_.size();
}
 void Model_V::clear_models() {
  models_.Clear();
}
 const ::Indriya::Core::Msgs::Model& Model_V::models(int index) const {
  // @@protoc_insertion_point(field_get:Indriya.Core.Msgs.Model_V.models)
  return models_.Get(index);
}
 ::Indriya::Core::Msgs::Model* Model_V::mutable_models(int index) {
  // @@protoc_insertion_point(field_mutable:Indriya.Core.Msgs.Model_V.models)
  return models_.Mutable(index);
}
 ::Indriya::Core::Msgs::Model* Model_V::add_models() {
  // @@protoc_insertion_point(field_add:Indriya.Core.Msgs.Model_V.models)
  return models_.Add();
}
 const ::google::protobuf::RepeatedPtrField< ::Indriya::Core::Msgs::Model >&
Model_V::models() const {
  // @@protoc_insertion_point(field_list:Indriya.Core.Msgs.Model_V.models)
  return models_;
}
 ::google::protobuf::RepeatedPtrField< ::Indriya::Core::Msgs::Model >*
Model_V::mutable_models() {
  // @@protoc_insertion_point(field_mutable_list:Indriya.Core.Msgs.Model_V.models)
  return &models_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Msgs
}  // namespace Core
}  // namespace Indriya

EX_REGISTER_STATIC_MSG("Indriya.Core.Msgs.Model_V", Model_V)
// @@protoc_insertion_point(global_scope)
