// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propagation_grid.proto

#ifndef PROTOBUF_propagation_5fgrid_2eproto__INCLUDED
#define PROTOBUF_propagation_5fgrid_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "propagation_particle.pb.h"
#include <boost/shared_ptr.hpp>
#include "MsgFactory.h"
// @@protoc_insertion_point(includes)

namespace Indriya {
namespace Core {
namespace Msgs {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_propagation_5fgrid_2eproto();
void protobuf_AssignDesc_propagation_5fgrid_2eproto();
void protobuf_ShutdownFile_propagation_5fgrid_2eproto();

class PropagationGrid;

// ===================================================================

class PropagationGrid : public ::google::protobuf::Message {
 public:
  PropagationGrid();
  virtual ~PropagationGrid();

  PropagationGrid(const PropagationGrid& from);

  inline PropagationGrid& operator=(const PropagationGrid& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PropagationGrid& default_instance();

  void Swap(PropagationGrid* other);

  // implements Message ----------------------------------------------

  inline PropagationGrid* New() const { return New(NULL); }

  PropagationGrid* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PropagationGrid& from);
  void MergeFrom(const PropagationGrid& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PropagationGrid* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Indriya.Core.Msgs.PropagationParticle particle = 1;
  int particle_size() const;
  void clear_particle();
  static const int kParticleFieldNumber = 1;
  const ::Indriya::Core::Msgs::PropagationParticle& particle(int index) const;
  ::Indriya::Core::Msgs::PropagationParticle* mutable_particle(int index);
  ::Indriya::Core::Msgs::PropagationParticle* add_particle();
  const ::google::protobuf::RepeatedPtrField< ::Indriya::Core::Msgs::PropagationParticle >&
      particle() const;
  ::google::protobuf::RepeatedPtrField< ::Indriya::Core::Msgs::PropagationParticle >*
      mutable_particle();

  // @@protoc_insertion_point(class_scope:Indriya.Core.Msgs.PropagationGrid)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Indriya::Core::Msgs::PropagationParticle > particle_;
  friend void  protobuf_AddDesc_propagation_5fgrid_2eproto();
  friend void protobuf_AssignDesc_propagation_5fgrid_2eproto();
  friend void protobuf_ShutdownFile_propagation_5fgrid_2eproto();

  void InitAsDefaultInstance();
  static PropagationGrid* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PropagationGrid

// repeated .Indriya.Core.Msgs.PropagationParticle particle = 1;
inline int PropagationGrid::particle_size() const {
  return particle_.size();
}
inline void PropagationGrid::clear_particle() {
  particle_.Clear();
}
inline const ::Indriya::Core::Msgs::PropagationParticle& PropagationGrid::particle(int index) const {
  // @@protoc_insertion_point(field_get:Indriya.Core.Msgs.PropagationGrid.particle)
  return particle_.Get(index);
}
inline ::Indriya::Core::Msgs::PropagationParticle* PropagationGrid::mutable_particle(int index) {
  // @@protoc_insertion_point(field_mutable:Indriya.Core.Msgs.PropagationGrid.particle)
  return particle_.Mutable(index);
}
inline ::Indriya::Core::Msgs::PropagationParticle* PropagationGrid::add_particle() {
  // @@protoc_insertion_point(field_add:Indriya.Core.Msgs.PropagationGrid.particle)
  return particle_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Indriya::Core::Msgs::PropagationParticle >&
PropagationGrid::particle() const {
  // @@protoc_insertion_point(field_list:Indriya.Core.Msgs.PropagationGrid.particle)
  return particle_;
}
inline ::google::protobuf::RepeatedPtrField< ::Indriya::Core::Msgs::PropagationParticle >*
PropagationGrid::mutable_particle() {
  // @@protoc_insertion_point(field_mutable_list:Indriya.Core.Msgs.PropagationGrid.particle)
  return &particle_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

typedef boost::shared_ptr<Indriya::Core::Msgs::PropagationGrid> PropagationGridPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace Msgs
}  // namespace Core
}  // namespace Indriya

typedef const boost::shared_ptr<Indriya::Core::Msgs::PropagationGrid const> ConstPropagationGridPtr;
// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_propagation_5fgrid_2eproto__INCLUDED
