//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/robot_behavior.proto
namespace experimot.msgs
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BehaviorDescription")]
  public partial class BehaviorDescription : global::ProtoBuf.IExtensible
  {
    public BehaviorDescription() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private experimot.msgs.BehaviorDescription.ExecutionType _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public experimot.msgs.BehaviorDescription.ExecutionType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private experimot.msgs.BehaviorDescription.ExecutionState _state;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public experimot.msgs.BehaviorDescription.ExecutionState state
    {
      get { return _state; }
      set { _state = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ExecutionType")]
    public enum ExecutionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Blocking", Value=0)]
      Blocking = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NonBlocking", Value=1)]
      NonBlocking = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ExecutionState")]
    public enum ExecutionState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Idle", Value=0)]
      Idle = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Running", Value=1)]
      Running = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error", Value=2)]
      Error = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RobotBehaviorModule")]
  public partial class RobotBehaviorModule : global::ProtoBuf.IExtensible
  {
    public RobotBehaviorModule() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<experimot.msgs.BehaviorDescription> _behaviors = new global::System.Collections.Generic.List<experimot.msgs.BehaviorDescription>();
    [global::ProtoBuf.ProtoMember(2, Name=@"behaviors", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<experimot.msgs.BehaviorDescription> behaviors
    {
      get { return _behaviors; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RobotBehaviorModules")]
  public partial class RobotBehaviorModules : global::ProtoBuf.IExtensible
  {
    public RobotBehaviorModules() {}
    
    private readonly global::System.Collections.Generic.List<experimot.msgs.RobotBehaviorModule> _modules = new global::System.Collections.Generic.List<experimot.msgs.RobotBehaviorModule>();
    [global::ProtoBuf.ProtoMember(1, Name=@"modules", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<experimot.msgs.RobotBehaviorModule> modules
    {
      get { return _modules; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}