//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/joint.proto
// Note: requires additional types generated from: axis.proto
// Note: requires additional types generated from: pose.proto
// Note: requires additional types generated from: sensor.proto
namespace Indriya.Core.Msgs
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Joint")]
  public partial class Joint : global::ProtoBuf.IExtensible
  {
    public Joint() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<double> _angle = new global::System.Collections.Generic.List<double>();
    [global::ProtoBuf.ProtoMember(3, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<double> angle
    {
      get { return _angle; }
    }
  
    private Indriya.Core.Msgs.Joint.Type _type = Indriya.Core.Msgs.Joint.Type.REVOLUTE;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Indriya.Core.Msgs.Joint.Type.REVOLUTE)]
    public Indriya.Core.Msgs.Joint.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _parent = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"parent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string parent
    {
      get { return _parent; }
      set { _parent = value; }
    }
    private uint _parent_id = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"parent_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint parent_id
    {
      get { return _parent_id; }
      set { _parent_id = value; }
    }
    private string _child = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"child", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string child
    {
      get { return _child; }
      set { _child = value; }
    }
    private uint _child_id = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"child_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint child_id
    {
      get { return _child_id; }
      set { _child_id = value; }
    }
    private Indriya.Core.Msgs.Pose _pose = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"pose", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Indriya.Core.Msgs.Pose pose
    {
      get { return _pose; }
      set { _pose = value; }
    }
    private Indriya.Core.Msgs.Axis _axis1 = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"axis1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Indriya.Core.Msgs.Axis axis1
    {
      get { return _axis1; }
      set { _axis1 = value; }
    }
    private Indriya.Core.Msgs.Axis _axis2 = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"axis2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Indriya.Core.Msgs.Axis axis2
    {
      get { return _axis2; }
      set { _axis2 = value; }
    }
    private double _cfm = default(double);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"cfm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double cfm
    {
      get { return _cfm; }
      set { _cfm = value; }
    }
    private double _bounce = default(double);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"bounce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double bounce
    {
      get { return _bounce; }
      set { _bounce = value; }
    }
    private double _velocity = default(double);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"velocity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double velocity
    {
      get { return _velocity; }
      set { _velocity = value; }
    }
    private double _fudge_factor = default(double);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"fudge_factor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double fudge_factor
    {
      get { return _fudge_factor; }
      set { _fudge_factor = value; }
    }
    private double _limit_cfm = default(double);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"limit_cfm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double limit_cfm
    {
      get { return _limit_cfm; }
      set { _limit_cfm = value; }
    }
    private double _limit_erp = default(double);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"limit_erp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double limit_erp
    {
      get { return _limit_erp; }
      set { _limit_erp = value; }
    }
    private double _suspension_cfm = default(double);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"suspension_cfm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double suspension_cfm
    {
      get { return _suspension_cfm; }
      set { _suspension_cfm = value; }
    }
    private double _suspension_erp = default(double);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"suspension_erp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double suspension_erp
    {
      get { return _suspension_erp; }
      set { _suspension_erp = value; }
    }
    private readonly global::System.Collections.Generic.List<Indriya.Core.Msgs.Sensor> _sensor = new global::System.Collections.Generic.List<Indriya.Core.Msgs.Sensor>();
    [global::ProtoBuf.ProtoMember(20, Name=@"sensor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Indriya.Core.Msgs.Sensor> sensor
    {
      get { return _sensor; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REVOLUTE", Value=1)]
      REVOLUTE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REVOLUTE2", Value=2)]
      REVOLUTE2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRISMATIC", Value=3)]
      PRISMATIC = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNIVERSAL", Value=4)]
      UNIVERSAL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BALL", Value=5)]
      BALL = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCREW", Value=6)]
      SCREW = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GEARBOX", Value=7)]
      GEARBOX = 7
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}