# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_behavior.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import request_pb2 as request__pb2
import response_pb2 as response__pb2
import param_pb2 as param__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot_behavior.proto',
  package='experimot.msgs',
  #syntax='proto2',
  serialized_pb=_b('\n\x14robot_behavior.proto\x12\x0e\x65xperimot.msgs\x1a\rrequest.proto\x1a\x0eresponse.proto\x1a\x0bparam.proto\"T\n\x11\x42\x65haviorArguments\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x12\x14\n\x0cplace_holder\x18\x03 \x02(\x08\x12\x0c\n\x04type\x18\x04 \x02(\t\"\xd2\x02\n\x13\x42\x65haviorDescription\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x15\n\rfunction_name\x18\x02 \x02(\t\x12.\n\x03\x61rg\x18\x03 \x03(\x0b\x32!.experimot.msgs.BehaviorArguments\x12?\n\x04type\x18\x04 \x02(\x0e\x32\x31.experimot.msgs.BehaviorDescription.ExecutionType\x12\x41\n\x05state\x18\x05 \x02(\x0e\x32\x32.experimot.msgs.BehaviorDescription.ExecutionState\".\n\rExecutionType\x12\x0c\n\x08\x42locking\x10\x00\x12\x0f\n\x0bNonBlocking\x10\x01\"2\n\x0e\x45xecutionState\x12\x08\n\x04Idle\x10\x00\x12\x0b\n\x07Running\x10\x01\x12\t\n\x05\x45rror\x10\x02\"\x86\x02\n\x13RobotBehaviorModule\x12\x0c\n\x04name\x18\x01 \x02(\t\x12$\n\x05param\x18\x02 \x03(\x0b\x32\x15.experimot.msgs.Param\x12\x36\n\tbehaviors\x18\x03 \x03(\x0b\x32#.experimot.msgs.BehaviorDescription\x12M\n\tresponder\x18\x04 \x01(\x0b\x32:.experimot.msgs.RobotBehaviorModule.RobotBehaviorResponder\x1a\x34\n\x16RobotBehaviorResponder\x12\x0c\n\x04Host\x18\x01 \x02(\t\x12\x0c\n\x04Port\x18\x02 \x02(\x05\"L\n\x14RobotBehaviorModules\x12\x34\n\x07modules\x18\x01 \x03(\x0b\x32#.experimot.msgs.RobotBehaviorModule')
  ,
  dependencies=[request__pb2.DESCRIPTOR,response__pb2.DESCRIPTOR,param__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BEHAVIORDESCRIPTION_EXECUTIONTYPE = _descriptor.EnumDescriptor(
  name='ExecutionType',
  full_name='experimot.msgs.BehaviorDescription.ExecutionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Blocking', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NonBlocking', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=411,
  serialized_end=457,
)
_sym_db.RegisterEnumDescriptor(_BEHAVIORDESCRIPTION_EXECUTIONTYPE)

_BEHAVIORDESCRIPTION_EXECUTIONSTATE = _descriptor.EnumDescriptor(
  name='ExecutionState',
  full_name='experimot.msgs.BehaviorDescription.ExecutionState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Idle', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Running', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Error', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=459,
  serialized_end=509,
)
_sym_db.RegisterEnumDescriptor(_BEHAVIORDESCRIPTION_EXECUTIONSTATE)


_BEHAVIORARGUMENTS = _descriptor.Descriptor(
  name='BehaviorArguments',
  full_name='experimot.msgs.BehaviorArguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='experimot.msgs.BehaviorArguments.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='experimot.msgs.BehaviorArguments.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='place_holder', full_name='experimot.msgs.BehaviorArguments.place_holder', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='experimot.msgs.BehaviorArguments.type', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  #syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=168,
)


_BEHAVIORDESCRIPTION = _descriptor.Descriptor(
  name='BehaviorDescription',
  full_name='experimot.msgs.BehaviorDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='experimot.msgs.BehaviorDescription.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='function_name', full_name='experimot.msgs.BehaviorDescription.function_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arg', full_name='experimot.msgs.BehaviorDescription.arg', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='experimot.msgs.BehaviorDescription.type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='experimot.msgs.BehaviorDescription.state', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BEHAVIORDESCRIPTION_EXECUTIONTYPE,
    _BEHAVIORDESCRIPTION_EXECUTIONSTATE,
  ],
  options=None,
  is_extendable=False,
  #syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=509,
)


_ROBOTBEHAVIORMODULE_ROBOTBEHAVIORRESPONDER = _descriptor.Descriptor(
  name='RobotBehaviorResponder',
  full_name='experimot.msgs.RobotBehaviorModule.RobotBehaviorResponder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Host', full_name='experimot.msgs.RobotBehaviorModule.RobotBehaviorResponder.Host', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Port', full_name='experimot.msgs.RobotBehaviorModule.RobotBehaviorResponder.Port', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  #syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=722,
  serialized_end=774,
)

_ROBOTBEHAVIORMODULE = _descriptor.Descriptor(
  name='RobotBehaviorModule',
  full_name='experimot.msgs.RobotBehaviorModule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='experimot.msgs.RobotBehaviorModule.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='experimot.msgs.RobotBehaviorModule.param', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='behaviors', full_name='experimot.msgs.RobotBehaviorModule.behaviors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responder', full_name='experimot.msgs.RobotBehaviorModule.responder', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ROBOTBEHAVIORMODULE_ROBOTBEHAVIORRESPONDER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  #syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=512,
  serialized_end=774,
)


_ROBOTBEHAVIORMODULES = _descriptor.Descriptor(
  name='RobotBehaviorModules',
  full_name='experimot.msgs.RobotBehaviorModules',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modules', full_name='experimot.msgs.RobotBehaviorModules.modules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  #syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=776,
  serialized_end=852,
)

_BEHAVIORDESCRIPTION.fields_by_name['arg'].message_type = _BEHAVIORARGUMENTS
_BEHAVIORDESCRIPTION.fields_by_name['type'].enum_type = _BEHAVIORDESCRIPTION_EXECUTIONTYPE
_BEHAVIORDESCRIPTION.fields_by_name['state'].enum_type = _BEHAVIORDESCRIPTION_EXECUTIONSTATE
_BEHAVIORDESCRIPTION_EXECUTIONTYPE.containing_type = _BEHAVIORDESCRIPTION
_BEHAVIORDESCRIPTION_EXECUTIONSTATE.containing_type = _BEHAVIORDESCRIPTION
_ROBOTBEHAVIORMODULE_ROBOTBEHAVIORRESPONDER.containing_type = _ROBOTBEHAVIORMODULE
_ROBOTBEHAVIORMODULE.fields_by_name['param'].message_type = param__pb2._PARAM
_ROBOTBEHAVIORMODULE.fields_by_name['behaviors'].message_type = _BEHAVIORDESCRIPTION
_ROBOTBEHAVIORMODULE.fields_by_name['responder'].message_type = _ROBOTBEHAVIORMODULE_ROBOTBEHAVIORRESPONDER
_ROBOTBEHAVIORMODULES.fields_by_name['modules'].message_type = _ROBOTBEHAVIORMODULE
DESCRIPTOR.message_types_by_name['BehaviorArguments'] = _BEHAVIORARGUMENTS
DESCRIPTOR.message_types_by_name['BehaviorDescription'] = _BEHAVIORDESCRIPTION
DESCRIPTOR.message_types_by_name['RobotBehaviorModule'] = _ROBOTBEHAVIORMODULE
DESCRIPTOR.message_types_by_name['RobotBehaviorModules'] = _ROBOTBEHAVIORMODULES

BehaviorArguments = _reflection.GeneratedProtocolMessageType('BehaviorArguments', (_message.Message,), dict(
  DESCRIPTOR = _BEHAVIORARGUMENTS,
  __module__ = 'robot_behavior_pb2'
  # @@protoc_insertion_point(class_scope:experimot.msgs.BehaviorArguments)
  ))
_sym_db.RegisterMessage(BehaviorArguments)

BehaviorDescription = _reflection.GeneratedProtocolMessageType('BehaviorDescription', (_message.Message,), dict(
  DESCRIPTOR = _BEHAVIORDESCRIPTION,
  __module__ = 'robot_behavior_pb2'
  # @@protoc_insertion_point(class_scope:experimot.msgs.BehaviorDescription)
  ))
_sym_db.RegisterMessage(BehaviorDescription)

RobotBehaviorModule = _reflection.GeneratedProtocolMessageType('RobotBehaviorModule', (_message.Message,), dict(

  RobotBehaviorResponder = _reflection.GeneratedProtocolMessageType('RobotBehaviorResponder', (_message.Message,), dict(
    DESCRIPTOR = _ROBOTBEHAVIORMODULE_ROBOTBEHAVIORRESPONDER,
    __module__ = 'robot_behavior_pb2'
    # @@protoc_insertion_point(class_scope:experimot.msgs.RobotBehaviorModule.RobotBehaviorResponder)
    ))
  ,
  DESCRIPTOR = _ROBOTBEHAVIORMODULE,
  __module__ = 'robot_behavior_pb2'
  # @@protoc_insertion_point(class_scope:experimot.msgs.RobotBehaviorModule)
  ))
_sym_db.RegisterMessage(RobotBehaviorModule)
_sym_db.RegisterMessage(RobotBehaviorModule.RobotBehaviorResponder)

RobotBehaviorModules = _reflection.GeneratedProtocolMessageType('RobotBehaviorModules', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTBEHAVIORMODULES,
  __module__ = 'robot_behavior_pb2'
  # @@protoc_insertion_point(class_scope:experimot.msgs.RobotBehaviorModules)
  ))
_sym_db.RegisterMessage(RobotBehaviorModules)


# @@protoc_insertion_point(module_scope)
