//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/sensor.proto
// Note: requires additional types generated from: pose.proto
// Note: requires additional types generated from: camerasensor.proto
// Note: requires additional types generated from: raysensor.proto
// Note: requires additional types generated from: contactsensor.proto
namespace experimot.msgs
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Sensor")]
  public partial class Sensor : global::ProtoBuf.IExtensible
  {
    public Sensor() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _parent;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"parent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string parent
    {
      get { return _parent; }
      set { _parent = value; }
    }
    private uint _parent_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"parent_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint parent_id
    {
      get { return _parent_id; }
      set { _parent_id = value; }
    }
    private string _type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private bool _always_on = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"always_on", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool always_on
    {
      get { return _always_on; }
      set { _always_on = value; }
    }
    private double _update_rate = default(double);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"update_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double update_rate
    {
      get { return _update_rate; }
      set { _update_rate = value; }
    }
    private experimot.msgs.Pose _pose = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"pose", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public experimot.msgs.Pose pose
    {
      get { return _pose; }
      set { _pose = value; }
    }
    private experimot.msgs.CameraSensor _camera = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"camera", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public experimot.msgs.CameraSensor camera
    {
      get { return _camera; }
      set { _camera = value; }
    }
    private experimot.msgs.RaySensor _ray = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"ray", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public experimot.msgs.RaySensor ray
    {
      get { return _ray; }
      set { _ray = value; }
    }
    private experimot.msgs.ContactSensor _contact = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"contact", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public experimot.msgs.ContactSensor contact
    {
      get { return _contact; }
      set { _contact = value; }
    }
    private bool _visualize = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"visualize", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool visualize
    {
      get { return _visualize; }
      set { _visualize = value; }
    }
    private string _topic = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"topic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string topic
    {
      get { return _topic; }
      set { _topic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}